language: node_js # Building with node.js
node_js:
  - stable # Download the stable node version

cache:
  directories:
    - node_modules

# Blocklist
branches:
  except:
    - gh-pages # will be deployed to gh-pages

script:
  - npm run lint # lints the project
  - npm run build # Generates the dist folder with built angular app

deploy:
  - provider: pages
    skip_cleanup: true # Prevent travis from cleaning out the branch before the deploy occurs
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master # Build only from master
    local_dir: dist # Only copy the dist contents
    # fqdn: dave0921.github.io/AngularApps
